name: daily_spend_tracker
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  flutter_localizations:
    sdk: flutter
  riverpod_annotation: ^2.3.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  flutter_slidable: ^3.1.1
  flutter_datetime_picker_plus: ^2.2.0
  url_launcher: ^6.3.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: 'assets/images/app_icon_ios.png'
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: 'assets/images/app_icon_adaptive_background.png'
  adaptive_icon_foreground: 'assets/images/app_icon_adaptive_foreground.png'
